### ISSUE TITLE
Trigger words

### ISSUE THREAD

**Issue by safaci2000** [OSAlt/nya-chan-bot#9]
When someone writes in general "bed" or "sleep now" or something -- maybe the bot can say goodnight to them? 

-- 
Can this be done without bumping up the security permission on the bot? 

This implementation under the old API found [here](https://github.com/Twentysix26/26-Cogs/tree/master/trigger) requires higher permissions which is not usable.

Maybe a bad implementation / changes in 1.0 allow for it?

**Comment by LucaVazz** [comment]
I don't think that for discord.py you need different permissions then the current ones to realize it.
`NyaChan.on_message` gets invoked regardless if the message starts with the bot's prefix or not.

**Comment by safaci2000** [comment]
right, but you're on invoking it.  You're monitoring all conversation.

ie.

user:"So I saw something really shiny on a window display"
bot: "Shiny? what where? squirrel? ... I want!!"

In the case above it'd react to someone saying "bed" or whatever trigger word you configure.

**Comment by LucaVazz** [comment]
I don't know if discord.py has a mechanism for configuring trigger words easily but if not it would always be possible to add something custom to the `on_message` function.

**Comment by lemonsaurus** [comment]
This issue is as old as my grandma but if you guys still want it, I opened a pull request with a typical implementation for this kind of thing.

**Comment by safaci2000** [comment]
Old as granny or not we'll take it.  Thanks for the PR.
